### ISSUE TITLE
CaseClauseError when enabling plugin

### ISSUE THREAD

**Issue by idanshm** [noxdafox/rabbitmq-cloudwatch-exporter#18]
Hi,

I am getting this exception when trying to enable the plugin:
```
** (CaseClauseError) no case clause matching: {:plugin_built_with_incompatible_erlang, 'hackney'}
    (rabbitmqctl) lib/rabbitmq/cli/plugins/plugins_helpers.ex:176: RabbitMQ.CLI.Plugins.Helpers.update_enabled_plugins/2
    (rabbitmqctl) lib/rabbitmq/cli/plugins/plugins_helpers.ex:98: RabbitMQ.CLI.Plugins.Helpers.update_enabled_plugins/4
    (rabbitmqctl) lib/rabbitmq/cli/plugins/commands/enable_command.ex:98: anonymous fn/6 in RabbitMQ.CLI.Plugins.Commands.EnableCommand.do_run/2
    (elixir) lib/stream.ex:1179: anonymous fn/2 in Stream.iterate/2
    (elixir) lib/stream.ex:1354: Stream.do_unfold/4
    (elixir) lib/stream.ex:1405: Enumerable.Stream.do_each/4
    (elixir) lib/stream.ex:849: Stream.do_enum_transform/10
    (elixir) lib/stream.ex:1405: Enumerable.Stream.do_each/4
```

**Comment by noxdafox** [comment]
Hello,

you are not providing enough information.

Please specify your versions of RabbiMQ and Erlang.

**Comment by idanshm** [comment]
Hi,
RabbitMQ: {rabbit,"RabbitMQ","3.7.3"}
Erlang: Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [kernel-poll:false]

**Comment by noxdafox** [comment]
The version of Erlang is too old and incompatible with the one which was used to build the plugin (21).

I would recommend you to upgrade both Erlang and RMQ versions. If this is not feasible, then you shall build the plugin with your version of Erlang. You can follow the instructions on the README to build the plugin.
